version: "3.8"
services:
  trendfusion-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped
    container_name: trendfusion-api
    networks:
      - trendfusion-network

networks:
  trendfusion-network:
    driver: bridge
