FastAPI:
  image: 654654248202.dkr.ecr.ap-south-1.amazonaws.com/trendfusion-ai-app:latest # ECR image path
  port: 80
  env:
    FA_USER_COLLECTION: users
    FA_DB_NAME: ai-trends
    FA_MONGO_URI: mongodb+srv://fa:R9y8pdxXzuw2JT6@ai-trends.onofaev.mongodb.net/?retryWrites=true&w=majority&appName=ai-trends
    GROQ_API_KEY: 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
    OPEN_SEARCH_USER: krakenops
    OPEN_SEARCH_PASSWORD: "@Krakenops007"
    OPEN_SEARCH_HOST: https://search-krakenops-products-i2db6hx4fdyavi5aw7cgzxjn5u.ap-south-1.es.amazonaws.com
    KRAKENOPS_BUCKET: krakenops
    TRENDICLES_NEURAL_ID: 669b9454ebdb13c63bb0d9e1
    TRENDICLES_CORE_COLLECTION: trendicles_core
    THIRD_AI_KEY: E36464-0801C9-DD90A8-94DB5C-8EDA4E-V3
    AWS_ACCESS_KEY_ID: AKIAZQ3DPCUFPOXJXVBV
    AWS_SECRET_ACCESS_KEY: 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
    FA_WARDROBE_COLLECTION: wardrobe
    FA_SIZE_CHART_COLLECTION: size_charts
    BODY_GRAM_API_KEY: sGLWnVI3hjNMFHGjmUPj762y74TXxzx9ReTkiITRdwa
    BODY_GRAM_ORG_ID: org_1rKXJvmMdXsXwpnQuy3yfZ
    BODY_GRAM_BUCKET: trendfusion-api
    BODY_GRAM_SCAN_COLLECTION: bodygram_user_scans
    REDIS_PORT: 6379
Redis:
  image: redis:latest
  port: 6379 # This is the port that Redis will listen on in the cluster
